---
# Vagrant hostname and IP configuration.
vagrant_hostname: magentotest.dev
vagrant_ip: 192.168.88.89
vagrant_user: vagrant

# A list of synced folders, with the keys 'local_path', 'destination', 'id', and
# a 'type' of [nfs|rsync|smb] (leave empty for slow native shares).
vagrant_synced_folders:
  # The first synced folder will be used for the default Magento installation.
  - local_path: ../magentovm
    destination: /var/www/magento
    id: magento
    type: nfs
    create: true

# Memory and CPU to use for this VM.
vagrant_memory: 1024
vagrant_cpus: 2

# Set this to false if you are using a different site deployment strategy and
# would like to configure 'vagrant_synced_folders' and 'apache_vhosts' manually.
install_magento: true

# Settings for building a Magento site from a makefile (if 'install_magento'
# is 'true').
magento_version: 1.9.1.0
magento_core_path: "/var/www/magento"
magento_domain: "magentotest.dev"
magento_site_name: "Magento Test Site"
# Sample data may to take a really long time to download...
magento_install_sample_data: "no"
magento_mysql_database: magento_development
magento_mysql_user: magento
magento_mysql_password: magento

# Apache VirtualHosts. Add one for each site you are running inside the VM. For
# multisite deployments, you can point multiple servernames at one documentroot.
apache_vhosts:
  - {servername: "{{ magento_domain }}", documentroot: "{{ magento_core_path }}"}
  - {servername: "local.xhprof.com", documentroot: "/usr/share/php/xhprof_html"}

# MySQL Databases and users.
mysql_databases:
  - name: magento_development
    encoding: utf8
    collation: utf8_general_ci

mysql_users:
  - name: magento
    host: "%"
    password: magento
    priv: "magento_development.*:ALL"

# Comment out any extra utilities you don't want to install.
installed_extras:
  - mailhog
  - memcached
  - phpmyadmin
  # - solr
  - xdebug
  - xhprof

# You can configure almost anything else on the server in the rest of this file.
mysql_root_password: root

firewall_allowed_tcp_ports:
  - "22"
  - "25"
  - "80"
  - "443"
  - "8025"
  - "8080"
  - "8443"
  - "8983"

# PHP Configuration. Currently-supported versions: 5.5, 5.6, 7.0 (experimental).
php_version: "5.5"
php_memory_limit: "192M"
php_display_errors: "On"
php_realpath_cache_size: "1024K"
php_sendmail_path: "/usr/sbin/ssmtp -t"

# Disable main XDebug components unless needed.
php_xdebug_coverage_enable: 0
php_xdebug_default_enable: 0

solr_version: "4.10.4"
solr_xms: "64M"
solr_xmx: "128M"
